// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGviRqQvw3PYcxhuvlt0iCkBYkSkS6HZY',
    appId: '1:853069479534:web:973dde58797bc2aec8b07f',
    messagingSenderId: '853069479534',
    projectId: 'contact-manager-1d6a8',
    authDomain: 'contact-manager-1d6a8.firebaseapp.com',
    storageBucket: 'contact-manager-1d6a8.appspot.com',
    measurementId: 'G-57BPNFK5W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uOVFQH9bcxy22lvZ6f4iNaXY1Z5qOG8',
    appId: '1:853069479534:android:ced55e7f59384882c8b07f',
    messagingSenderId: '853069479534',
    projectId: 'contact-manager-1d6a8',
    storageBucket: 'contact-manager-1d6a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefPak9XqmsW68kW3UUM8SqLw9IDrLbTE',
    appId: '1:853069479534:ios:53b85eb656b8f67cc8b07f',
    messagingSenderId: '853069479534',
    projectId: 'contact-manager-1d6a8',
    storageBucket: 'contact-manager-1d6a8.appspot.com',
    iosClientId: '853069479534-n9f6gkbi2155krdqb9k2qfb6na3gnkhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefPak9XqmsW68kW3UUM8SqLw9IDrLbTE',
    appId: '1:853069479534:ios:53b85eb656b8f67cc8b07f',
    messagingSenderId: '853069479534',
    projectId: 'contact-manager-1d6a8',
    storageBucket: 'contact-manager-1d6a8.appspot.com',
    iosClientId: '853069479534-n9f6gkbi2155krdqb9k2qfb6na3gnkhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactManager',
  );
}
